defaults:
  - data: ifs_era
  - hydra: default
  - model: transformer
  - trainer: default
  - training: default
  - callbacks:
      - early_stopping
      - model_checkpoint
  - logger:
      - tensorboard

exp_name: MISSING
logging_level: DEBUG
seed: 42
